-- TODO: Make lightline config work (showing the branch name)
-- vim.g.lightline = {
--        active =  {
--          left = { { 'mode', 'paste' },
--                    { 'gitbranch', 'readonly', 'filename', 'modified' } }
--        },
--        component_function = {
--          gitbranch = 'FugitiveHead'
--        },
-- }
