#!/usr/bin/env bash

function usage() {
    echo "Usage: dec-to-hex <decimal-number>"
}

if [[ "$#" -eq 0 ]];then
        echo "No arguments specified."
        usage
        exit 1
fi

DEC=$1

printf '%x\n' $DEC
exit 0
#!/usr/bin/env bash



