#!/usr/bin/env bash
# This script uses flameshot to interactively
# take a screenshot, then passes that screenshot
# into tesseract to perform ocr, and copies
# the result of the ocr to your clipboard
# Then opens yomichan search or focuses it if
# it is already open

function usage() {
    echo "Usage: flameshot-ocr [language]"
}


if [[ "$#" -eq 0 ]];then
        echo "No arguments specified."
        usage
        exit 1
fi

save_path="/tmp/flameshot-screenshot.png"
lang=$1

flameshot gui -r > "$save_path"
output=$(ocr "$save_path" "$lang")
echo "$output"
yomichan-search

exit 0
