#!/usr/bin/env python3
import sys
import os

def help() -> None:
    print("Usage: fourcc <code>", file=sys.stderr)

def make_fourcc(code: int) -> str:
        char1 = chr((code >> 0) & 255)
        char2 = chr((code >> 8) & 255)
        char3 = chr((code >> 16) & 255)
        char4 = chr((code >> 24) & 255)
        fourcc_string = f"{char1}{char2}{char3}{char4}"
        return fourcc_string


def main():
    if len(sys.argv) > 2:
        help()
        exit(1)

    if len(sys.argv) == 2:
        fourcc_input = sys.argv[1]
        try:
            fourcc = int(fourcc_input)
        except Exception:
            print(f"Failed to parse input {fourcc_input} as an integer. Exiting.", file=sys.stderr)
            exit(1)

        fourcc_string = make_fourcc(fourcc)
        print(fourcc_string)

    else:
        # read input from stdin
        for line in map(str.strip, sys.stdin):
            if len(line) == 0:
                continue
            try:
                fourcc = int(line)
            except Exception:
                print("{line}: couldn't parse as integer")
                continue

            fourcc_string = make_fourcc(fourcc)
            print(fourcc_string)

if __name__ == "__main__":
    main()
