#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from nvr.nvr import main
import subprocess

terminal_script = "/home/negosaki/bin/terminal"

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    subprocess.run(terminal_script, shell=True)
    sys.exit(main())

