#!/usr/bin/env bash
# This script is a wrapper for tesseract to make it more
# convenient to use

function usage() {
    echo "Usage: ocr [file] [language]"
}

if (( $# < 2 )); then
    usage
    exit 1
fi

filename=$1
lang=$2
outfile="/tmp/tesseract-output"

tesseract "$1" $outfile -l "$2"
cat "$outfile".txt
exit 0
