#!/usr/bin/env bash
# if alacritty terminal is already open, switch to
# window. Else, open alacritty
# Make a keyboard shortcut to this bash script
# for a very convenient terminal experience

if [[ $(xdotool search --onlyvisible --class alacritty)  ]]; then
    xdotool search --onlyvisible --class alacritty windowactivate
else
    alacritty
fi
